application: app-engine-starter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# The reason you can keep this is because of the static_url method
# which uses unique id from the app to refresh cache on each deploy
# just need to make sure you prefix all your static files with it
default_expiration: "30d"

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?tests$
- \.svn
- \.git
- ^\.svn/.*


builtins:
- appstats: off #/_ah/stats/
- remote_api: on #/_ah/remote_api/
- deferred: on

handlers:
- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /(js|css|img)/(.*)
  static_files: static/\1/\2
  upload: static/(js|css|img)/.*

# Endpoints handler (in services/__init__.py)
- url: /_ah/spi/.*
  script: services.application

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: "latest"