application: app-engine-starter
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: yes

automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: 1s
  max_pending_latency: 1s

# The reason you can keep this is because of the static_url method
# which uses unique id from the app to refresh cache on each deploy
# just need to make sure you prefix all your static files with it
default_expiration: "365d"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests$
- ^src$
- ^.*node_modules(/.*)?

builtins:
- appstats: off #/_ah/stats/
- remote_api: on #/_ah/remote_api/
- deferred: on

handlers:
- url: /(robots\.txt|humans\.txt|crossdomain\.xml|favicon\.ico)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml|favicon\.ico)

- url: /(js|css|img)/(.*)
  static_files: static/\1/\2
  upload: static/(js|css|img)/.*

- url: /(admin|task)/.*
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: "latest"
- name: PIL
  version: "1.1.7"

includes:
- app-local.yaml